base_url = "https://tsubaki.dev"
title = "Tsubaki's Blog"
description = "Here is tsubaki's personal blog."

default_language = "en"

build_search_index = true
generate_feeds = true

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

minify_html = true
theme = "anemone"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[extra]
author = "TsubakiDev"
list_pages = true
display_author = true
toc = true

header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/blog", name_en = "/blog/" },
]
